[project]
name = "numalgos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "pip>=24.3.1",
    "scipy>=1.14.1",
]
